/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cinema;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventas.Cliente;
import ventas.Venta;

/**
 *
 * @author Maria Camila Ochoa C
 */
public class frmCinema extends javax.swing.JFrame implements ActionListener {
    
    private static ImageIcon imgSillaPreferencialReservada= new ImageIcon("/Cinema/preferencial ocupada.png");
    private static ImageIcon imgSillaSencillaReservada= new ImageIcon("/Cinema/Silla sencilla ocupada.png");
    private static ImageIcon imgSillaOcupada= new ImageIcon("/Cinema/Silla sencilla ocupada.png");
    
    
    
    private ArrayList <Venta> Ventas = new ArrayList<>();
    private HashMap <Integer, Silla> Sillas = new HashMap<>();
    private HashMap <String, Cliente> Clientes = new HashMap<>();
    private Silla sillaSeleccionada;
    private JButton botonSillaSeleccionada;
    private Cliente clienteSeleccionado;


    
//    private static imageIcon imgSillaPreferencialReservada= new imageIcon(); 
//    esto es para indicat las imagenes que se le pusieron a las imagenes pero yo no pude cargarlas

    /**
     * Creates new form frmCinema
     */
    public frmCinema() {
        initComponents();
        this.btn1.addActionListener(this);
        this.btn2.addActionListener(this);
        this.btn3.addActionListener(this);
        this.btn4.addActionListener(this);
        this.btn5.addActionListener(this);
        this.btn6.addActionListener(this);
        this.btn7.addActionListener(this);
        this.btn8.addActionListener(this);
        this.btn9.addActionListener(this);
        
        
        
        crearDatos();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextDocumento = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        btnCompletarVenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LabelSillaSeleccionada = new javax.swing.JLabel();
        LabelPrecio1 = new javax.swing.JLabel();
        btnCambiarFuncion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        btn1.setBackground(new java.awt.Color(51, 255, 204));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn1.setText("Silla libre");
        btn1.setActionCommand("7");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 255, 204));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn2.setText("Silla libre");
        btn2.setActionCommand("7");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 255, 204));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn3.setText("Silla libre");
        btn3.setActionCommand("7");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 255, 204));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/Silla sencilla.png"))); // NOI18N
        btn4.setText("Silla libre");
        btn4.setActionCommand("1");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 255, 204));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/Silla sencilla.png"))); // NOI18N
        btn5.setText("Silla libre");
        btn5.setActionCommand("1");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 255, 204));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/Silla sencilla.png"))); // NOI18N
        btn6.setText("Silla libre");
        btn6.setActionCommand("1");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 255, 204));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn7.setText("Silla libre");
        btn7.setActionCommand("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 255, 204));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn8.setText("Silla libre");
        btn8.setActionCommand("7");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 255, 204));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cinema/preferencial.png"))); // NOI18N
        btn9.setText("Silla libre");
        btn9.setActionCommand("7");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        jLabel5.setText("Pantalla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel3.setText("Silla selesccionada");

        jLabel4.setText("Precio de la silla");

        jLabel6.setText("Información cliente");

        jLabel7.setText("Documento");

        jLabel8.setText("Nombre");

        jTextDocumento.setText("jTextField1");
        jTextDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDocumentoFocusLost(evt);
            }
        });

        jTextNombre.setText("jTextField1");

        btnCompletarVenta.setText("Completar venta");
        btnCompletarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarVentaActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelSillaSeleccionada.setText("Silla seleccionada");
        LabelSillaSeleccionada.setToolTipText("");

        LabelPrecio1.setText("Precio silla");
        LabelPrecio1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelSillaSeleccionada))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCompletarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23)))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addComponent(LabelPrecio1)
                    .addGap(23, 23, 23)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelSillaSeleccionada))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompletarVenta)
                    .addComponent(jButton1))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(LabelPrecio1)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );

        btnCambiarFuncion.setText("Cambiar Funcion");
        btnCambiarFuncion.setActionCommand("Cambiar Funcion");
        btnCambiarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFuncionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        tlVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cliente", "No Silla", "Valor Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tlVentas);

        jLabel1.setText("Tabla ventas");

        btnTest.setText("test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarFuncion)
                    .addComponent(btnTest))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCambiarFuncion)
                                .addGap(293, 293, 293)
                                .addComponent(btnTest))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.sillaSeleccionada != null){
            
        this.sillaSeleccionada.cambiarEstado(Estado.DISPONIBLE);
            
        this.resolverImagenBoton(this.botonSillaSeleccionada, sillaSeleccionada);            
        
            limpiarDatos();
            
            
            this.botonSillaSeleccionada.setIcon(imgSillaOcupada);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpiarDatos() {
        this.sillaSeleccionada= null;
        this.botonSillaSeleccionada= null;
        this.LabelSillaSeleccionada.setText("");
        this.LabelPrecio1.setText("");
        this.jTextDocumento.setText("");
        this.jTextNombre.setText("");
        this.clienteSeleccionado= null;
    }

    private void btnCambiarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarFuncionActionPerformed

    private void btnCompletarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarVentaActionPerformed
        if (this.sillaSeleccionada == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una silla");
            return;
        }
        
        if (jTextDocumento.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el documento");
            return;
        }
        if (jTextNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre");
            return;
        }
        
        if(clienteSeleccionado == null){
            Cliente cliente= new Cliente(jTextNombre.getText(), jTextDocumento.getText());
            Clientes.put(cliente.getDocumento(),cliente );
            this.clienteSeleccionado= cliente;
        }
        
        Venta venta= new Venta(new Date());
        venta.setCliente(clienteSeleccionado);
        venta.setSilla(sillaSeleccionada);
        venta.setValorVenta(Double.valueOf(this.LabelPrecio1.getText()));
        Ventas.add(venta);
        this.agregarVentaATabla(venta);
        
        this.sillaSeleccionada.cambiarEstado(Estado.OCUPADA);
        this.resolverImagenBoton(this.botonSillaSeleccionada, sillaSeleccionada);
        this.limpiarDatos();
        
      
    }//GEN-LAST:event_btnCompletarVentaActionPerformed

    private void jTextDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDocumentoFocusLost
        Cliente cliente= this.buscarCliente(jTextDocumento.getText());
        if(cliente != null){
            this.clienteSeleccionado= cliente;
            this.jTextNombre.setText(cliente.getNombre());
        }
    }//GEN-LAST:event_jTextDocumentoFocusLost

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        Cliente cliente1= new Cliente("Maria", "1234");
        Cliente cliente2= new Cliente("Camila", "5678");
        Silla silla6= this.Sillas.get(6);
        
        Venta venta1= new Venta(new Date());
        venta1.setCliente(cliente1);
        venta1.setSilla(silla6);
        venta1.setValorVenta(20000);
        
//        Object [] fila= {"fecha", "Nombre cliente", 100, 10000}; una forma inicial de hacerlo
        Object [] fila= venta1.getDatosComoFila();
        
        DefaultTableModel modeloDeDatos= (DefaultTableModel) this.tlVentas.getModel();
        modeloDeDatos.addRow(fila);
        
        
    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCinema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPrecio1;
    private javax.swing.JLabel LabelSillaSeleccionada;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCambiarFuncion;
    private javax.swing.JButton btnCompletarVenta;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDocumento;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTable tlVentas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        JButton btnSilla= (JButton) e.getSource();
        
        btnSilla.setIcon(imgSillaOcupada); // NOI18N
        
        this.seleccionarSilla(btnSilla);

//        System.out.println("Accion en: " + e.getActionCommand());
    }

    private void crearDatos() {
        
        Silla silla1= new SillaDeshabilitada(1, "Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla2= new SillaDeshabilitada(2, "Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla3= new SillaDeshabilitada(3, "Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla4= new Silla(4,"Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla5= new Silla(5,"Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla6= new Silla(6,"Silla sencilla Ocupada.png", Estado.DISPONIBLE);
        Silla silla7= new SillaPreferencial(7,"preferencial ocupada", Estado.DISPONIBLE);
        Silla silla8= new SillaPreferencial(8,"preferencial ocupada", Estado.DISPONIBLE);
        Silla silla9= new SillaPreferencial(9,"preferencial ocupada", Estado.DISPONIBLE);
        
        this.Sillas.put(1, silla1);
        this.Sillas.put(2, silla2);
        this.Sillas.put(3, silla3);
        this.Sillas.put(4, silla4);
        this.Sillas.put(5, silla5);
        this.Sillas.put(6, silla6);
        this.Sillas.put(7, silla7);
        this.Sillas.put(8, silla8);
        this.Sillas.put(9, silla9);
        
                
          
        
    }
    
    public void seleccionarSilla (JButton btnSilla){
        Integer noSilla= Integer.valueOf(btnSilla.getActionCommand());
        Silla sillaSeleccionada= this.Sillas.get(noSilla);
        
        switch (sillaSeleccionada.getEstado()){
            case DISPONIBLE :
                reservarSilla (btnSilla, sillaSeleccionada);
                break;
            case RESERVADA:
                JOptionPane.showMessageDialog(this, "Esta silla está en proceso de venta");
            break;
            
            case OCUPADA:
                Venta venta= buscarVenta(noSilla);
                JOptionPane.showMessageDialog(this, "Esta silla está ocuapda por "+ venta.getCliente());

            default:
        }
    }
    
    
    public void reservarSilla (JButton btnSilla, Silla sillaSeleccionada){
        int diaSemana= getDiaSemana();
        double precio= sillaSeleccionada.calcularPrecio(diaSemana);
        if (precio==-1){
            JOptionPane.showMessageDialog(this, "Silla deshabilitada termporalmente");
            return;
        }
        
        
        this.sillaSeleccionada= sillaSeleccionada;
        this.botonSillaSeleccionada= btnSilla;
        
        sillaSeleccionada.cambiarEstado(Estado.RESERVADA);
        this.resolverImagenBoton(btnSilla, sillaSeleccionada);
                
        this.LabelSillaSeleccionada.setText(String.valueOf(sillaSeleccionada.getNoSilla()));
        this.LabelPrecio1.setText(String.valueOf(precio));
        btnSilla.setIcon(imgSillaOcupada);
        


           
}
        
        
        
        
    

    private int getDiaSemana() {
        Date fechaActual= new Date();
        Calendar calendar= Calendar.getInstance();
        
        calendar.setTime(fechaActual);
//        calendar.add(Calendar.DAY_OF_MONTH, 1);
//con lo anterior se le pueden agregar dias
        
        return calendar.get(Calendar.DAY_OF_WEEK);
        
        
//        LocalDate localdate= LocalDate.of (2021, Month.AUGUST, 7);
//        Date date2= Date.from (localdate.atStartOfDay(ZoneId.systemDefault()).toInstant());
//        localdate.getDayOfWeek();
//Lo anterior es otr aforma de hacerlo con una libreria de java que es LocalDate

 
    }

    private void resolverImagenBoton(JButton boton, Silla silla) {
        String apellidoImg= "";
        
        switch (silla.getEstado()){
            case DISPONIBLE:
                apellidoImg=" sencilla.png" ;
                break;
            case OCUPADA:
                apellidoImg= " sencilla ocupada.jpg";
                break;
            case RESERVADA:
                apellidoImg= " sencilla ocupada.jpg";
                break;
        }
        
    
         ImageIcon imagen= new ImageIcon("/Cinema/"+ silla.getImagen()+ apellidoImg);
         boton.setIcon(imagen);
         
       
    }

    private Cliente buscarCliente(String documento) {
        return this.Clientes.get(documento);
        
    }

    private Venta buscarVenta(Integer noSilla) {
        
        for(Venta venta:Ventas){
            if(venta.getSilla().getNoSilla()== noSilla);
            return venta;
            
        }
        
        return null;
    }

    private void agregarVentaATabla(Venta venta) {
        
        DefaultTableModel modeloDeDatos= (DefaultTableModel) this.tlVentas.getModel();
        modeloDeDatos.addRow(venta.getDatosComoFila());
    }
}

